use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
secret_key_base =
  case System.get_env("SECRET_KEY_BASE") do
    v when is_binary(v) and v != "" -> v
    _ -> raise "SECRET_KEY_BASE is missing"
  end

config :zcash_explorer, ZcashExplorerWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: secret_key_base

# Do not print debug messages in production
config :logger, level: :info
